<a href="https://colab.research.google.com/github/Luc1lfer/CCDATRCL_ASSIGNMENT_COM221/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy

## Numpy


In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [4]:
arr[0]

1

In [5]:
arr = np.array([[1,2], [3,4], [5,6]])
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
arr.ndim

2

In [7]:
arr.itemsize

8

In [8]:
arr.shape

(3, 2)

In [9]:
arr = np.array([[1,2], [3,4], [5,6]], dtype=np.float64)
arr

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [11]:
arr = np.zeros([2,4])
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
arr = np.ones([1,4])
arr

array([[1., 1., 1., 1.]])

In [13]:
arr = np.arange(5)
print(arr)

[0 1 2 3 4]


In [14]:
arr.ndim

1

In [15]:
arr.shape

(5,)

In [17]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr.ndim)
print(arr.shape)

[1 2 3 4 5]
1
(5,)


##String Functions

In [20]:
arr1 = np.array(["hello", "hi"])
arr2 = np.array(["abc", "xyz"])

In [22]:
arrstring = np.char.add(arr1, arr2)
arrstring

array(['helloabc', 'hixyz'], dtype='<U8')

In [23]:
arr = np.array(["Hello"])

In [24]:
arr = np.char.lower(arr)
arr

array(['hello'], dtype='<U5')

In [25]:
arr = np.char.upper(arr)
arr

array(['HELLO'], dtype='<U5')

In [27]:
namearray = np.array(["Allen Siaton"])


In [28]:
arr = np.char.split(namearray)
arr

array([list(['Allen', 'Siaton'])], dtype=object)

##Array Manipulation

In [29]:
arr = np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
arr.shape

(9,)

In [32]:
arr = np.arange(9)
print(arr)

print("dimension", arr.ndim)
print("shape", arr.shape)

[0 1 2 3 4 5 6 7 8]
dimension 1
shape (9,)


In [31]:
arr2 = arr.reshape(3,3)
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
arr = np.arange(8)
arr2 = arr.reshape(3,3)
arr2

ValueError: cannot reshape array of size 8 into shape (3,3)

In [38]:
arr = np.arange(8)
arr2 = arr.reshape(2,4)
arr2

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [39]:
arr = np.arange(8)
arr2 = arr.reshape(2,2,2)
arr2

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [40]:
arr2.shape

(2, 2, 2)

In [41]:
arr2[1]

array([[4, 5],
       [6, 7]])

In [60]:
arr2[1,[0,1],0]

array([4, 6])

In [64]:
arr2[0,1]

array([2, 3])

In [66]:
arr3 = arr2.flatten()
arr3

array([0, 1, 2, 3, 4, 5, 6, 7])

In [67]:
arr = np.arange(12).reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [68]:
transposedarr = np.transpose(arr)
transposedarr

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

##Arithmetic Operations

In [69]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [70]:
b = np.array([10, 10, 10])
c = np.add(a,b)
c

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [71]:
b = np.array([10, 10, 10])
c = np.add(a,b)
c

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [72]:
b = np.array([10, 10, 10])
c = np.subtract(a,b)
c

array([[-10,  -9,  -8],
       [ -7,  -6,  -5],
       [ -4,  -3,  -2]])

##Other Functions

In [73]:
a = np.linspace(1,3,10)
a

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

In [74]:
a = np.array([(1,2,3), (3,4,5)])
print(a.sum(axis=1))

[ 6 12]


In [76]:
a = np.array([(1,2,3), (3,4,5)])
print(a.sum(axis=0))

[4 6 8]


In [77]:
print(np.std(a))

1.2909944487358056


In [75]:
a


array([[1, 2, 3],
       [3, 4, 5]])